spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: dbteser
    password: dbt7504t7504!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 265804754287-d828dul7u5l29dr14c2e4na3qcrot4kn
            client-secret: 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
            scope:
              - email
              - profile
logging:
  level:
    org.hibernate.SQL: debug

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot